apiVersion: batch/v1
kind: Job
metadata:
  name: music-download
spec:
  template:
    spec:
      containers:
      - name: downloader
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - |
          wget -O /music/cancion1.mp3 "https://drive.google.com/uc?export=download&id=1ckyF6BsGLh9alUhLP8-3XDnX0DcFUxM-"
          wget -O /music/cancion2.mp3 "https://drive.google.com/uc?export=download&id=1WtmKlPASnAX_xUyQDDZer-waZ740m1MQ"
        volumeMounts:
        - name: music
          mountPath: /music
      restartPolicy: OnFailure
      volumes:
      - name: music
        persistentVolumeClaim:
          claimName: music-mstream-0  